Rel1cx/eslint-react

README.md, package.json, packages/eslint-plugin-debug/src/rules/class-component.md, packages/eslint-plugin-debug/src/rules/function-component.md, packages/eslint-plugin-jsx/src/rules/no-array-index-key.md, packages/eslint-plugin-jsx/src/rules/no-duplicate-key.md, packages/eslint-plugin-jsx/src/rules/no-leaked-conditional-rendering.md, packages/eslint-plugin-jsx/src/rules/no-missing-key.md, packages/eslint-plugin-jsx/src/rules/no-misused-comment-in-textnode.md, packages/eslint-plugin-jsx/src/rules/no-script-url.md, packages/eslint-plugin-jsx/src/rules/prefer-shorthand-boolean.md, packages/eslint-plugin-naming-convention/src/rules/filename-extension.md, packages/eslint-plugin-naming-convention/src/rules/filename.md, packages/eslint-plugin-react/src/rules/no-constructed-context-value.md, packages/eslint-plugin-react/src/rules/no-dangerously-set-innerhtml-with-children.md, packages/eslint-plugin-react/src/rules/no-dangerously-set-innerhtml.md, packages/eslint-plugin-react/src/rules/no-string-refs.md, packages/eslint-plugin-react/src/rules/no-unstable-default-props.md, packages/eslint-plugin-react/src/rules/no-unstable-nested-components.md, packages/eslint-plugin/eslint-doc-generator.config.ts, patches/eslint-doc-generator@1.5.2.patch, pnpm-lock.yaml
fix #21 
Because `pathRuleDoc` only supports strings as parameters, I added a [patch](https://github.com/eslint-react/eslint-react/pull/24/files#diff-326a391fda728e1bca8db7e259ce95c93d130f8c60a829fa73fca0ffdfab0401). Maybe we can submit a PR later.
=> docs: fix automatic document generation for multiple packages

cspell.json, package.json, packages/ast/package.json, packages/core/package.json, packages/eslint-plugin-debug/package.json, packages/eslint-plugin-hooks/package.json, packages/eslint-plugin-jsx/package.json, packages/eslint-plugin-jsx/src/rules/no-leaked-conditional-rendering.spec.ts, packages/eslint-plugin-jsx/src/rules/no-leaked-conditional-rendering.ts, packages/eslint-plugin-naming-convention/package.json, packages/eslint-plugin-react/package.json, packages/eslint-plugin/package.json, packages/jsx/package.json, packages/jsx/src/value.ts, packages/shared/package.json, packages/tools/package.json, packages/types/package.json
Improving the implementation of `jsx/no-leaked-conditional-rendering`, should completely avoid the problems in the existing technology like https://github.com/jsx-eslint/eslint-plugin-react/issues/3292
=> refactor: improve jsx/no-leaked-conditional-rendering

packages/eslint-plugin-jsx/src/rules/no-leaked-conditional-rendering.ts
Run eslint
Can not get `ts7.TypeFlags.Null` from `import*as ts7 from"typescript"`
Because in `typescript.js` file
```
...
// src/typescript/typescript.ts
var require_typescript = __commonJS({
"src/typescript/typescript.ts"(exports, module2) {
init_ts6();
init_ts6();
if (typeof console !== "undefined") {
Debug.loggingHost = {
log(level, s) {
switch (level) {
case 1 /* Error */:
return console.error(s);
case 2 /* Warning */:
return console.warn(s);
case 3 /* Info */:
return console.log(s);
case 4 /* Verbose */:
return console.log(s);
}
}
};
}
module2.exports = ts_exports2;
}
});
return require_typescript();
})();
if (typeof module !== "undefined" && module.exports) { module.exports = ts; }
```
=> fix: can not import typescript in esm

.eslintrc.cjs, README.md, package.json, packages/ast/package.json, packages/core/package.json, packages/eslint-plugin-debug/package.json, packages/eslint-plugin-jsx/package.json, packages/eslint-plugin-jsx/src/rules/no-leaked-conditional-rendering.ts, packages/eslint-plugin-naming-convention/package.json, packages/eslint-plugin-react-hooks/package.json, packages/eslint-plugin-react/package.json, packages/eslint-plugin-react/src/rules/no-unsafe-target-blank.ts, packages/eslint-plugin/package.json, packages/jsx/package.json, packages/shared/package.json, packages/tools/package.json, packages/types/package.json, pnpm-lock.yaml
=> fix: use stable `typescript` cuz `tseslint` doesn't support ts rc

CHANGELOG.md, packages/eslint-plugin-jsx/src/rules/no-useless-fragment.md, packages/eslint-plugin-jsx/src/rules/no-useless-fragment.spec.ts, packages/eslint-plugin-jsx/src/rules/no-useless-fragment.ts, packages/jsx/docs/README.md, packages/jsx/src/fragment.ts
=> refactor: react-no-useless-fragment always allow expressions

CHANGELOG.md, packages/plugins/eslint-plugin-react/src/rules/no-unstable-nested-components.spec.ts, packages/plugins/eslint-plugin-react/src/rules/no-unstable-nested-components.ts
=> refactor: Improve rule `react/no-unstable-nested-components`, make its behavior closer to facebook/react#25360

CHANGELOG.md, packages/plugins/eslint-plugin-react/src/rules/no-constructed-context-value.ts, packages/plugins/eslint-plugin-react/src/rules/no-create-ref.ts
=> fix: same kind of error inside a component should not only be reported once in rule `react/no-create-ref` and `react/no-constructed-context-value`.

website/pages/rules/no-useless-fragment.mdx
This pull request updates the documentation to reflect the changes in the `no-useless-fragment` rule. The rule previously had an `allowExpressions` option, which controlled whether single expressions in a fragment were allowed. [This option has been removed](https://github.com/Rel1cx/eslint-react/pull/188), and the rule now always allows single expressions in a fragment.
- The removal of the `allowExpressions` option was not reflected in the documentation, potentially causing confusion for users transitioning from [`eslint-plugin-react`](https://github.com/jsx-eslint/eslint-plugin-react) to `@eslint-react`.
- By updating the documentation, we provide clear guidance on the current behavior of the `no-useless-fragment` rule.
=> Update Documentation for `no-useless-fragment` Rule

website/pages/docs/rules/avoid-shorthand-fragment.mdx, website/pages/docs/rules/overview.md, website/pages/docs/rules/prefer-read-only-props.mdx
When configuring this plugin in my project, I've noticed some inconsistencies in the documentation, related to the rules. This pull request fixes them.
I've also noticed, that `avoid-shorthand-fragment` and `prefer-shorthand-fragment` rules have identical descriptions, though they do opposite things:
* https://eslint-react.xyz/docs/rules/avoid-shorthand-fragment#what-it-does
* https://eslint-react.xyz/docs/rules/prefer-shorthand-fragment#what-it-does
Makes sense to fix it by maintainers, but it is not the scope of this pull request.
=> Fix rules' documentation

packages/plugins/eslint-plugin-react-web-api/src/index.ts, packages/plugins/eslint-plugin-react-web-api/src/rules/no-leaked-interval.spec.ts, packages/plugins/eslint-plugin-react-web-api/src/rules/no-leaked-interval.ts, packages/plugins/eslint-plugin/src/index.ts, website/pages/docs/rules/_meta.ts, website/pages/docs/rules/web-api-no-leaked-interval.mdx
=> feat: add rule 'no-leaked-interval', closes #727

packages/plugins/eslint-plugin-react-hooks-extra/src/rules/prefer-use-state-lazy-initialization.spec.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/prefer-use-state-lazy-initialization.ts, packages/tools/docs/type-aliases/ArrayElement.md, packages/tools/docs/type-aliases/Narrow.md, packages/utilities/ast/src/get-nested-call-expressions.ts, packages/utilities/ast/src/get-nested-expressions-of-type.ts, packages/utilities/ast/src/get-nested-new-expressions.ts, packages/utilities/ast/src/index.ts, pnpm-lock.yaml
This PR adds support for detecting redundant constructor invocations where `useState` is used. For example:
```tsx
function Foo() {
const [bar, setBar] = useState(new Bar()); // <- `new Bar()` is redundant on subsequent renders
return '...';
}
```
=> feat: add support for constructors in `hooks-extra/prefer-use-state-lazy-initialization`

packages/plugins/eslint-plugin-react-hooks-extra/src/index.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-direct-set-state-in-use-effect.spec.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-direct-set-state-in-use-layout-effect.spec.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-direct-set-state-in-use-layout-effect.ts, packages/plugins/eslint-plugin/src/index.ts, website/next.config.mjs, website/pages/docs/rules/_meta.ts, website/pages/docs/rules/hooks-extra-no-direct-set-state-in-use-layout-effect.mdx, website/pages/docs/rules/overview.md
=> Undeprecate `hooks-extra-no-direct-set-state-in-use-layout-effect` and remove it from recommended presets, closes #839

package.json, packages/plugins/eslint-plugin-react-x/src/rules/no-leaked-conditional-rendering.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-leaked-conditional-rendering.ts, pnpm-lock.yaml
=> fix(plugins/x): 'no-leaked-conditional-rendering' report empty string, closes #853

packages/core/docs/functions/isInitializedFromReact.md, packages/core/src/is-initialized-from-react.ts, packages/plugins/eslint-plugin-react-debug/src/rules/is-from-react.spec.ts, packages/plugins/eslint-plugin-react-dom/src/index.ts, packages/plugins/eslint-plugin-react-naming-convention/src/rules/use-state.spec.ts, packages/plugins/eslint-plugin-react-web-api/src/index.ts, packages/plugins/eslint-plugin-react-x/src/index.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-children-count.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-children-for-each.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-children-map.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-children-only.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-children-to-array.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-useless-fragment.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/prefer-shorthand-fragment.spec.ts, packages/shared/docs/variables/INITIAL_ESLINT_REACT_SETTINGS.md, packages/shared/src/schemas.ts, packages/shared/src/settings.ts
=> refactor: update the default behavior of import check, closes #858

packages/plugins/eslint-plugin-react-x/src/rules/no-unstable-context-value.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-unstable-default-props.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-unstable-default-props.ts, packages/utilities/var/src/construction.ts
=> fix(plugins/x): fix 'no-unstable-rules' false positives

apps/website/content/docs/rules/overview.mdx, packages/plugins/eslint-plugin-react-naming-convention/src/rules/component-name.spec.ts, packages/plugins/eslint-plugin-react-naming-convention/src/rules/component-name.ts, packages/plugins/eslint-plugin-react-naming-convention/src/rules/filename-extension.spec.ts, packages/plugins/eslint-plugin-react-naming-convention/src/rules/filename-extension.ts, packages/plugins/eslint-plugin-react-naming-convention/src/rules/use-state.md, packages/plugins/eslint-plugin-react-naming-convention/src/rules/use-state.spec.ts, packages/plugins/eslint-plugin-react-naming-convention/src/rules/use-state.ts, packages/plugins/eslint-plugin-react-web-api/src/rules/no-leaked-event-listener.spec.ts, packages/plugins/eslint-plugin-react-web-api/src/rules/no-leaked-event-listener.ts, packages/plugins/eslint-plugin-react-web-api/src/rules/no-leaked-interval.spec.ts, packages/plugins/eslint-plugin-react-web-api/src/rules/no-leaked-interval.ts, packages/plugins/eslint-plugin-react-web-api/src/rules/no-leaked-resize-observer.spec.ts, packages/plugins/eslint-plugin-react-web-api/src/rules/no-leaked-resize-observer.ts, packages/plugins/eslint-plugin-react-web-api/src/rules/no-leaked-timeout.spec.ts, packages/plugins/eslint-plugin-react-web-api/src/rules/no-leaked-timeout.ts
=> refactor: improve error messages

apps/website/content/docs/rules/meta.json, apps/website/content/docs/rules/overview.md, packages/plugins/eslint-plugin-react-dom/src/plugin.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-find-dom-node.md, packages/plugins/eslint-plugin-react-dom/src/rules/no-flush-sync.md, packages/plugins/eslint-plugin-react-dom/src/rules/no-flush-sync.spec.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-flush-sync.ts
=> feat(plugins/dom): add 'no-flush-sync' rule

apps/website/content/docs/configurations.mdx, apps/website/content/docs/configurations.tsx, packages/shared/src/schemas.ts
=> docs: make 'strictImportCheck' setting public

apps/website/content/docs/configurations.mdx, apps/website/content/docs/configurations.tsx, packages/core/src/hook/is.ts, packages/core/src/utils/is-from-react.ts, packages/plugins/eslint-plugin-react-debug/src/rules/is-from-react.spec.ts, packages/plugins/eslint-plugin-react-naming-convention/src/rules/use-state.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-children-count.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-children-for-each.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-children-map.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-children-only.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-children-to-array.spec.ts, packages/shared/docs/functions/defineSettings.md, packages/shared/docs/variables/DEFAULT_ESLINT_REACT_SETTINGS.md, packages/shared/src/schemas.ts, packages/shared/src/settings.ts
=> refactor: rename 'strictImportCheck' to 'skipImportCheck'

examples/vite-react-dom-with-ts-blank-eslint-parser-app/eslint.config.js, packages/plugins/eslint-plugin-react-naming-convention/src/configs/recommended.ts, packages/plugins/eslint-plugin/src/configs/recommended.ts
=> feat: add 'naming-convention/use-state' and 'naming-convention/context-name' to recommended presets

packages/plugins/eslint-plugin-react-dom/src/rules/no-missing-button-type.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-missing-iframe-sandbox.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-namespace.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-unsafe-iframe-sandbox.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-unsafe-target-blank.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-void-elements-with-children.ts, packages/plugins/eslint-plugin-react-dom/src/utils/get-element-type-on-jsx-and-dom.ts, packages/plugins/eslint-plugin-react-dom/src/utils/index.ts, packages/plugins/eslint-plugin-react-naming-convention/src/plugin.ts, packages/plugins/eslint-plugin-react-naming-convention/src/rules/component-name.md, packages/plugins/eslint-plugin-react-naming-convention/src/rules/component-name.spec.ts, packages/plugins/eslint-plugin-react-naming-convention/src/rules/component-name.ts, packages/plugins/eslint-plugin-react-naming-convention/src/rules/filename-extension.ts, packages/plugins/eslint-plugin-react-naming-convention/src/rules/filename.ts, packages/plugins/eslint-plugin-react-x/src/plugin.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-context-provider.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-unstable-context-value.ts, packages/utilities/jsx/src/get-element-type.ts, packages/utilities/jsx/src/index.ts, packages/utilities/jsx/src/is-kind-of-element.ts
=> fix: rework 'naming-convention/component-name' rule

packages/core/docs/functions/isReactHookCallWithNameAlias.md, packages/core/src/hook/is.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/hooks/use-no-direct-set-state-in-use-effect.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-direct-set-state-in-use-effect.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-direct-set-state-in-use-layout-effect.ts
=> refactor(plugins/hooks-extra): improve code reusability

packages/plugins/eslint-plugin-react-x/src/rules/no-unstable-context-value.spec.ts, packages/utilities/var/src/get-variable-node.ts, packages/utilities/var/src/is-node-value-equal.ts
=> fix(utilities/var): fix variable init node retrieval, fixes #964

packages/plugins/eslint-plugin-react-hooks-extra/src/hooks/use-no-direct-set-state-in-use-effect.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-direct-set-state-in-use-effect.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-children-prop.md
=> fix(plugins/hooks-extra): misidentification of 'set' function in IIFE inside of hooks as its inside of 'useEffect', 'useLayoutEffect', closes #967

packages/plugins/eslint-plugin-react-naming-convention/src/rules/component-name.ts, packages/plugins/eslint-plugin-react-naming-convention/src/rules/filename.ts, packages/plugins/eslint-plugin-react-naming-convention/src/utils/index.ts, packages/plugins/eslint-plugin-react-naming-convention/src/utils/regexp.ts, scripts/update-website.ts
=> refactor: add toRegExp utility for regex handling in naming conventions

apps/website/content/docs/getting-started/javascript.mdx, apps/website/content/docs/getting-started/meta.json, apps/website/lib/source.ts, apps/website/source.config.ts, apps/website/tsconfig.json, examples/dual-react-dom-lib/eslint.config.mjs, examples/next-app/eslint.config.mjs, examples/vite-react-dom-app/eslint.config.js, examples/vite-react-dom-js-app/eslint.config.js, examples/vite-react-dom-js-with-babel-eslint-parser-app/eslint.config.js, examples/vite-react-dom-with-ts-blank-eslint-parser-app/eslint.config.js
=> docs: update eslint configs in examples to use extends

packages/plugins/eslint-plugin-react-naming-convention/src/rules/use-state.md, packages/plugins/eslint-plugin-react-naming-convention/src/rules/use-state.spec.ts, packages/plugins/eslint-plugin-react-naming-convention/src/rules/use-state.ts
=> refactor(naming-convention/use-state): enhance error messaging and docs, closes #980

packages/plugins/eslint-plugin-react-hooks-extra/src/rules/prefer-use-state-lazy-initialization.spec.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/prefer-use-state-lazy-initialization.ts
=> fix: `hooks-extra/prefer-use-state-lazy-initialization` false positive on `useState(use(promise))` closes #999

apps/website/package.json, packages/plugins/eslint-plugin-react-dom/src/rules/no-unknown-property.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-array-index-key.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-leaked-conditional-rendering.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-missing-key.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-useless-fragment.ts, packages/shared/docs/README.md, packages/shared/docs/functions/createReport.md, packages/shared/src/create-report.ts, packages/shared/src/index.ts, packages/shared/src/report.ts
=> refactor: add 'createReport' helper

packages/core/src/hook/hook-name.ts, packages/core/src/hook/is.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/prefer-use-state-lazy-initialization.spec.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/prefer-use-state-lazy-initialization.ts
=> fix: enhance `hooks-extra/prefer-use-state-lazy-initialization` to correctly detect other hooks called within `useState(...)`

packages/plugins/eslint-plugin-react-x/src/rules/no-leaked-conditional-rendering.ts
=> fix: the requested module 'ts-api-utils' does not provide an export named 'unionConstituents', closes #1009

apps/website/content/docs/rules/meta.json, apps/website/content/docs/rules/overview.mdx, packages/plugins/eslint-plugin-react-x/src/configs/recommended-typescript.ts, packages/plugins/eslint-plugin-react-x/src/configs/recommended.ts, packages/plugins/eslint-plugin-react-x/src/plugin.ts, packages/plugins/eslint-plugin-react-x/src/rules/jsx-no-undef.md, packages/plugins/eslint-plugin-react-x/src/rules/jsx-no-undef.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/jsx-no-undef.ts, packages/plugins/eslint-plugin/src/configs/all.ts, packages/plugins/eslint-plugin/src/configs/core.ts
=> feat: add `react-x/jsx-no-undef` rule, closes #1016

apps/website/content/docs/rules/overview.mdx, packages/plugins/eslint-plugin-react-hooks-extra/README.md, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/prefer-use-state-lazy-initialization.md, packages/plugins/eslint-plugin/src/configs/recommended.ts
=> feat: add `'hooks-extra/prefer-use-state-lazy-initialization` rule to recommended presets

packages/core/docs/functions/isDeclaredInRenderPropLoose.md, packages/core/docs/functions/isInsideRenderMethod.md, packages/core/docs/functions/isRenderFunctionLoose.md, packages/core/docs/functions/isRenderPropLoose.md, packages/core/src/component/component-lifecycle.ts, packages/core/src/component/component-render-prop.ts, packages/plugins/eslint-plugin-react-x/src/rules/avoid-shorthand-boolean.md, packages/plugins/eslint-plugin-react-x/src/rules/avoid-shorthand-fragment.md, packages/plugins/eslint-plugin-react-x/src/rules/jsx-no-undef.md, packages/plugins/eslint-plugin-react-x/src/rules/jsx-uses-vars.md, packages/plugins/eslint-plugin-react-x/src/rules/no-class-component.md, packages/plugins/eslint-plugin-react-x/src/rules/no-comment-textnodes.md, packages/plugins/eslint-plugin-react-x/src/rules/no-context-provider.md, packages/plugins/eslint-plugin-react-x/src/rules/no-forward-ref.md, packages/plugins/eslint-plugin-react-x/src/rules/no-missing-key.md, packages/plugins/eslint-plugin-react-x/src/rules/no-unstable-default-props.md
=> docs: improve examples in rules docs

apps/website/content/docs/rules/overview.mdx, packages/plugins/eslint-plugin-react-naming-convention/src/configs/recommended.ts, packages/plugins/eslint-plugin-react-naming-convention/src/rules/context-name.md, packages/plugins/eslint-plugin/src/configs/recommended.ts
=> feat: enable `context-name` rule in recommended presets

packages/plugins/eslint-plugin-react-x/src/rules/jsx-uses-react.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/jsx-uses-react.ts, packages/plugins/eslint-plugin-react-x/src/rules/jsx-uses-vars.spec.ts, packages/utilities/kit/src/JsxRuntime/JsxRuntimeOptions.ts, packages/utilities/kit/src/RegExp.ts, test/fixtures/tsconfig.jsx-preserve.json, test/fixtures/tsconfig.jsx-react-native.json, test/fixtures/tsconfig.jsx-react.json, test/rule-tester.ts
=> feat(react-x): enhance `jsx-uses-react` rule to support inline jsx annotation

packages/core/src/hook/hook-name.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-unnecessary-use-prefix.spec.ts
=> fix: fixed `hooks-extra/no-unnecessary-use-prefix` case sensitivity fails, closes #1053

apps/website/content/docs/faq.mdx, packages/plugins/eslint-plugin-react-dom/src/rules/no-dangerously-set-innerhtml-with-children.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-dangerously-set-innerhtml.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-find-dom-node.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-flush-sync.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-hydrate.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-render-return-value.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-render.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-script-url.ts, packages/utilities/kit/src/RE.ts
=> docs: minor improvements

packages/core/src/hook/hook-hierarchy.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-unnecessary-use-callback.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-unnecessary-use-memo.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/prefer-use-state-lazy-initialization.ts, packages/plugins/eslint-plugin-react-naming-convention/src/rules/use-state.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-forward-ref.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-implicit-key.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-missing-component-display-name.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-missing-context-display-name.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-use-context.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-useless-forward-ref.ts, packages/plugins/eslint-plugin-react-x/src/rules/prefer-shorthand-boolean.ts
=> fix: use smaller error marker range to reduce visual noise

packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-unnecessary-use-prefix.md, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-unnecessary-use-prefix.spec.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-unnecessary-use-prefix.ts, pnpm-lock.yaml
=> feat(hooks-extra): update `no-unnecessary-use-prefix` to skip well-known hooks

.pkgs/configs/eslint.js, .pkgs/configs/eslint.ts, packages/plugins/eslint-plugin-react-debug/src/rules/jsx.spec.ts, packages/plugins/eslint-plugin-react-debug/src/rules/jsx.ts, packages/plugins/eslint-plugin-react-x/src/rules/jsx-uses-react.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/jsx-uses-react.ts, packages/utilities/kit/docs/@eslint-react/namespaces/JsxConfig/README.md, packages/utilities/kit/docs/@eslint-react/namespaces/JsxConfig/functions/getFromAnnotation.md, packages/utilities/kit/docs/@eslint-react/namespaces/JsxConfig/functions/getFromContext.md, packages/utilities/kit/docs/@eslint-react/namespaces/JsxConfig/functions/make.md, packages/utilities/kit/docs/@eslint-react/namespaces/JsxConfig/interfaces/JsxConfig.md, packages/utilities/kit/docs/@eslint-react/namespaces/JsxConfig/type-aliases/JsxConfig.md, packages/utilities/kit/docs/@eslint-react/namespaces/JsxConfig/variables/JsxEmit.md, packages/utilities/kit/src/JsxConfig/JsxConfig.ts, test/rule-tester.ts
=> fix: fixed named export 'JsxEmit' not found, closes #1095

.pkgs/configs/eslint.js, .pkgs/configs/eslint.ts, apps/website/app/(home)/page.tsx, apps/website/app/layout.config.tsx, apps/website/app/overrides.css, apps/website/components/Background.tsx, apps/website/package.json, pnpm-lock.yaml
=> feat(website): add background effect to homepage

apps/website/content/docs/rules/meta.json, apps/website/content/docs/rules/overview.mdx, packages/plugins/eslint-plugin-react-x/src/configs/recommended.ts, packages/plugins/eslint-plugin-react-x/src/plugin.ts, packages/plugins/eslint-plugin-react-x/src/rules/jsx-key-before-spread.md, packages/plugins/eslint-plugin-react-x/src/rules/jsx-key-before-spread.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/jsx-key-before-spread.ts, packages/plugins/eslint-plugin/src/configs/all.ts, packages/plugins/eslint-plugin/src/configs/x.ts
=> feat: add `jsx-key-before-spread`, closes #1093, closes #1087

packages/plugins/eslint-plugin-react-dom/src/rules/no-void-elements-with-children.spec.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-void-elements-with-children.ts
=> fix: 'polymorphicPropName' not work with 'no-void-elements-with-children'

packages/plugins/eslint-plugin-react-hooks-extra/src/hooks/use-no-direct-set-state-in-use-effect.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-direct-set-state-in-use-effect.spec.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/utils/index.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/utils/is-function-of-immediately-invoked.ts
=> fix: fixed `use-no-direct-set-state-in-use-effect` deferred setState calls detection, closes #1117

packages/core/src/jsx/jsx-detection.ts, packages/plugins/eslint-plugin-react-x/src/rules/prefer-read-only-props.spec.ts
=> fix: fixed jsx detection method not respect SkipEmptyArray hint, closes #1122

apps/website/content/docs/configuration/configure-language-config.mdx, apps/website/content/docs/configuration/meta.json, apps/website/content/docs/faq.mdx, apps/website/content/docs/getting-started/javascript.mdx, apps/website/content/docs/getting-started/typescript.mdx, apps/website/content/docs/glossary.mdx
=> docs: update references from 'Language Config' to 'Project Config' across documentation

packages/plugins/eslint-plugin-react-dom/src/rules/no-missing-button-type.spec.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-missing-button-type.ts
=> fix: fixed suggestions for 'no-missing-button-type' rule

packages/plugins/eslint-plugin-react-dom/src/rules/no-missing-button-type.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-missing-iframe-sandbox.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-unsafe-iframe-sandbox.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-unsafe-target-blank.spec.ts, packages/plugins/eslint-plugin-react-dom/src/rules/no-unsafe-target-blank.ts, packages/plugins/eslint-plugin-react-dom/src/utils/index.ts, packages/plugins/eslint-plugin-react-dom/src/utils/resolve-attribute.ts
=> refactor: code optimizations

packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-unnecessary-use-prefix.md
=> docs: minor fixes

packages/plugins/eslint-plugin-react-x/src/rules/no-leaked-conditional-rendering.ts
=> refactor: remove unnecessary 'switch (true)' usage

apps/website/content/docs/faq.mdx, apps/website/content/docs/meta.json, apps/website/content/docs/migration.mdx
I would appreciate a double check by maintainers; feel free to push to this branch with corrections.
=> feat: add comparison table, closes #915

packages/plugins/eslint-plugin-react-x/src/rules/no-forbidden-props.md, packages/plugins/eslint-plugin-react-x/src/rules/no-forbidden-props.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-forbidden-props.ts
This rule adds support for banning certain component properties. This is useful for our project, which uses `preact`, and so we discourage the use of `className`. In addition, we discourage the usage of `snake_case` variables. This PR adds the ability to lint those errors. This rule was partially written with Cursor. Closes #1155
=> feat: `forbid-component-props`, closes #1155

packages/plugins/eslint-plugin-react-x/src/rules/no-unnecessary-use-prefix.ts, packages/utilities/kit/src/ContextDetection.ts
- Reorder condition checks in no-unnecessary-use-prefix rule for better performance
- Check for hooks with calls first before checking well-known hooks
- Extract isViMock helper function from isViMockCallback for better code reuse
- Improve isViMockCallback to use AST.isFunction for broader function type support
- Add proper JSDoc documentation for isViMock function
=> fix: improve hook detection logic and vi.mock utilities

scripts/update-readme.ts, scripts/update-version.ts, scripts/update-website.ts, scripts/verify-lockfile.ts
=> refactor(scripts): migrate scripts to `effect` and `effect-platform`

packages/plugins/eslint-plugin-react-x/src/rules/no-nested-lazy-component-declarations.spec.ts, packages/plugins/eslint-plugin-react-x/src/rules/no-nested-lazy-component-declarations.ts, pnpm-lock.yaml
=> fix: rule name and message id key mismatch in no-nested-lazy-component-declarations

packages/plugins/eslint-plugin-react-dom/src/rules/no-unknown-property.mdx, packages/plugins/eslint-plugin-react-dom/src/rules/no-unknown-property.ts
- Update rule implementation in no-unknown-property.ts
- Update rule documentation in no-unknown-property.mdx
- Update all config to include latest changes
=> refactor: update `dom/no-unknown-property` rule implementation

packages/plugins/eslint-plugin-react-debug/src/index.ts, packages/plugins/eslint-plugin-react-dom/src/index.ts, packages/plugins/eslint-plugin-react-hooks-extra/src/index.ts, packages/plugins/eslint-plugin-react-naming-convention/src/index.ts, packages/plugins/eslint-plugin-react-web-api/src/index.ts, packages/plugins/eslint-plugin-react-x/src/index.ts, packages/shared/docs/README.md, packages/shared/docs/functions/getConfigAdapters.md, packages/shared/src/get-config-adapters.ts, packages/shared/src/index.ts
=> refactor: replace custom config functions with getConfigAdapters utility

.pkgs/configs/eslint.js, .pkgs/configs/eslint.ts, README.md, apps/website/content/docs/getting-started/typescript.mdx, apps/website/eslint.config.ts, eslint.config.ts, packages/plugins/eslint-plugin-react-debug/README.md, packages/plugins/eslint-plugin-react-dom/README.md, packages/plugins/eslint-plugin-react-hooks-extra/README.md, packages/plugins/eslint-plugin-react-naming-convention/README.md, packages/plugins/eslint-plugin-react-web-api/README.md, packages/plugins/eslint-plugin-react-x/README.md, packages/plugins/eslint-plugin/README.md
=> docs: replace `tseslint.config` with `defineConfig`

.github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/rule_request.yml
=> docs: enhance feature and rule request issue templates

apps/website/content/docs/rules/overview.mdx, packages/plugins/eslint-plugin-react-naming-convention/src/configs/recommended.ts, packages/plugins/eslint-plugin-react-naming-convention/src/rules/use-state.mdx, packages/plugins/eslint-plugin/src/configs/recommended.ts
=> Update recommended presets, closes #1251

packages/plugins/eslint-plugin-react-x/src/rules/no-forbidden-props.ts
[no-forbidden-props](https://github.com/Rel1cx/eslint-react/blob/62590fd7579e1c3d63ddbcc56caf9a8fabcde681/packages/plugins/eslint-plugin-react-x/src/rules/no-forbidden-props.ts#L43) rule currently allows extra properties to be passed in options object, which should not be allowed. This makes it easier for typos in rule options to go unnoticed.
This PR simply disallows extra properties in this rule's schema.
=> fix: disallow extra properties in rule options
