Rel1cx/eslint-react

package.json
packages/ast/package.json
packages/ast/src/unary.ts
packages/core/package.json
packages/eslint-plugin-debug/package.json
packages/eslint-plugin-hooks/package.json
packages/eslint-plugin-jsx/package.json
packages/eslint-plugin-jsx/src/rules/no-leaked-conditional-rendering.spec.ts
packages/eslint-plugin-jsx/src/rules/no-leaked-conditional-rendering.ts
packages/eslint-plugin-naming-convention/package.json
packages/eslint-plugin-react/package.json
packages/eslint-plugin/package.json
packages/jsx/package.json
packages/shared/package.json
packages/tools/package.json
packages/types/package.json

…rendering
chore: bump version to 0.8.0

fix: `isAlternateGuarded` in jsx/no-leaked-conditional-rendering

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/PULL_REQUEST_TEMPLATE.md
package.json
packages/ast/package.json
packages/core/package.json
packages/eslint-plugin-debug/package.json
packages/eslint-plugin-hooks/package.json
packages/eslint-plugin-hooks/src/rules/ensure-custom-hooks-using-other-hooks.md
packages/eslint-plugin-jsx/package.json
packages/eslint-plugin-naming-convention/package.json
packages/eslint-plugin-react/package.json
packages/eslint-plugin/package.json
packages/jsx/package.json
packages/shared/package.json
packages/shared/src/constants.ts
packages/tools/package.json
packages/types/package.json
pnpm-lock.yaml
website/pages/docs/packages/_meta.json
website/theme.config.tsx

docs: update project url

---

packages/eslint-plugin/package.json

ci: remove unneeded scripts in npm scripts

---

package.json
packages/eslint-plugin-debug/src/rules/class-component.md
packages/eslint-plugin-debug/src/rules/function-component.md
packages/eslint-plugin-debug/src/rules/hooks.md
pnpm-lock.yaml

docs: remove unneeded sections from debug rule's documents

---

.github/workflows/test.yml

ci: update job name in test action

---

.eslintrc.cjs
website/styles/base.scss
website/styles/overrides.scss

chore(website): update title font

---

packages/eslint-plugin-jsx/src/rules/no-leaked-conditional-rendering.ts

refactor: revert commit 041a36

---

package.json
packages/ast/package.json
packages/core/package.json
packages/eslint-plugin-debug/package.json
packages/eslint-plugin-hooks/package.json
packages/eslint-plugin-jsx/package.json
packages/eslint-plugin-naming-convention/package.json
packages/eslint-plugin-react/package.json
packages/eslint-plugin/package.json
packages/jsx/package.json
packages/shared/package.json
packages/tools/package.json
packages/types/package.json

release: 0.8.3

---

.github/CONTRIBUTING.md
.vscode/settings.json
cspell.json

docs: update contributing guide

---

website/theme.config.tsx

docs(website): update image import

---

website/pages/index.mdx

chore(website): update image url

---

pnpm-lock.yaml
website/package.json

chore: update deps

---

packages/eslint-plugin-react/src/rules/no-children-count.md
packages/eslint-plugin-react/src/rules/no-children-count.ts
packages/eslint-plugin-react/src/rules/no-children-for-each.md
packages/eslint-plugin-react/src/rules/no-children-for-each.ts
packages/eslint-plugin-react/src/rules/no-children-map.md
packages/eslint-plugin-react/src/rules/no-children-map.ts
packages/eslint-plugin-react/src/rules/no-children-only.md
packages/eslint-plugin-react/src/rules/no-children-only.ts
packages/eslint-plugin-react/src/rules/no-children-to-array.md
packages/eslint-plugin-react/src/rules/no-children-to-array.ts

docs: improve no-children-methods rules doc

---

packages/eslint-plugin-react/src/index.ts
packages/eslint-plugin-react/src/rules/no-children-prop.md
packages/eslint-plugin-react/src/rules/no-children-prop.spec.ts
packages/eslint-plugin-react/src/rules/no-children-prop.ts
packages/eslint-plugin-react/src/rules/no-unsafe-target-blank.ts
packages/eslint-plugin/src/index.ts
packages/jsx/docs/README.md
packages/jsx/src/prop/get-prop.ts
website/pages/rules/_meta.json
website/pages/rules/overview.md

feat: add no-children-prop, closes #101

---

packages/eslint-plugin-hooks/src/rules/ensure-custom-hooks-using-other-hooks.md
packages/eslint-plugin-jsx/src/rules/no-leaked-conditional-rendering.md
packages/eslint-plugin-jsx/src/rules/no-spreading-key.ts
packages/eslint-plugin-jsx/src/rules/prefer-shorthand-boolean.ts
packages/eslint-plugin-jsx/src/rules/prefer-shorthand-fragment.ts
packages/eslint-plugin-naming-convention/src/rules/component-name.ts
packages/eslint-plugin-react/src/rules/no-children-in-void-dom-elements.ts
packages/eslint-plugin-react/src/rules/no-children-prop.ts
packages/eslint-plugin-react/src/rules/no-class-component.ts
packages/eslint-plugin-react/src/rules/no-dangerously-set-innerhtml-with-children.ts
packages/eslint-plugin-react/src/rules/no-dangerously-set-innerhtml.ts
packages/eslint-plugin-react/src/rules/no-missing-button-type.ts
packages/eslint-plugin-react/src/rules/no-missing-iframe-sandbox.ts
packages/eslint-plugin-react/src/rules/no-unsafe-iframe-sandbox.ts
packages/eslint-plugin-react/src/rules/prefer-destructuring-assignment.md
website/pages/rules/overview.md

docs: improve docs

---

package.json
packages/ast/package.json
packages/core/package.json
packages/eslint-plugin-debug/package.json
packages/eslint-plugin-hooks/package.json
packages/eslint-plugin-jsx/package.json
packages/eslint-plugin-naming-convention/package.json
packages/eslint-plugin-react/package.json
packages/eslint-plugin/package.json
packages/jsx/package.json
packages/shared/package.json
packages/tools/package.json
packages/types/package.json

release: 0.8.5-beta.0

---

package.json
packages/ast/package.json
packages/core/package.json
packages/eslint-plugin-debug/package.json
packages/eslint-plugin-hooks/package.json
packages/eslint-plugin-jsx/package.json
packages/eslint-plugin-naming-convention/package.json
packages/eslint-plugin-naming-convention/src/rules/component-name.md
packages/eslint-plugin-naming-convention/src/rules/filename-extension.md
packages/eslint-plugin-naming-convention/src/rules/filename.md
packages/eslint-plugin-naming-convention/src/rules/filename.spec.ts
packages/eslint-plugin-naming-convention/src/rules/filename.ts
packages/eslint-plugin-react/package.json
packages/eslint-plugin/package.json
packages/jsx/package.json
packages/shared/package.json
packages/tools/package.json
packages/types/package.json

refactor: naming-convention/filename default to `kebab-case`

---

packages/core/docs/README.md
packages/core/src/render-prop/is-render-prop.ts
packages/eslint-plugin-jsx/src/rules/no-leaked-conditional-rendering.ts
packages/eslint-plugin-react/src/rules/no-unstable-nested-components.ts
packages/jsx/docs/README.md
packages/jsx/src/misc.ts
packages/jsx/src/value.ts

refactor: update jsx value related behavior

---

package.json
packages/ast/package.json
packages/core/package.json
packages/eslint-plugin-debug/package.json
packages/eslint-plugin-jsx/package.json
packages/eslint-plugin-naming-convention/package.json
packages/eslint-plugin-react-hooks/package.json
packages/eslint-plugin-react/package.json
packages/eslint-plugin/package.json
packages/jsx/package.json
packages/shared/package.json
packages/tools/package.json
packages/types/package.json

chore: bump version to 0.8.5

---

package.json
packages/ast/package.json
packages/core/package.json
packages/eslint-plugin-debug/package.json
packages/eslint-plugin-jsx/package.json
packages/eslint-plugin-jsx/src/index.ts
packages/eslint-plugin-jsx/src/rules/no-complicated-conditional-rendering.md
packages/eslint-plugin-jsx/src/rules/no-complicated-conditional-rendering.spec.ts
packages/eslint-plugin-jsx/src/rules/no-complicated-conditional-rendering.ts
packages/eslint-plugin-naming-convention/package.json
packages/eslint-plugin-react-hooks/package.json
packages/eslint-plugin-react/package.json
packages/eslint-plugin/package.json
packages/eslint-plugin/src/index.ts
packages/jsx/package.json
packages/shared/package.json
packages/tools/package.json
packages/types/package.json
website/pages/rules/_meta.json

feat: add no-complicated-conditional-rendering, closes #105

---

packages/core/docs/README.md
packages/core/src/component/component-collector.ts
packages/core/src/component/component-init-path.ts
packages/eslint-plugin-debug/src/rules/function-component.spec.ts

feat: add getComponentInitPath and getComponentFlag

---

packages/eslint-plugin-react/src/rules/no-missing-component-display-name.md

docs: correct rule doc title

---

CHANGELOG.md
packages/core/docs/README.md
packages/core/src/hook/hook-call.ts
packages/core/src/hook/hook-collector.ts
packages/core/src/hook/hook.ts
packages/core/src/hook/index.ts
packages/eslint-plugin-debug/src/rules/react-hooks.spec.ts
packages/eslint-plugin-debug/src/rules/react-hooks.ts
packages/eslint-plugin-react-hooks/src/rules/ensure-custom-hooks-using-other-hooks.ts

refactor: `hookCollector` add `hookCalls` collect, remove `cost` field

---

packages/ast/docs/README.md
packages/ast/src/call.ts
packages/ast/src/index.ts
packages/eslint-plugin-react-hooks/src/index.ts
packages/eslint-plugin-react-hooks/src/rules/prefer-use-state-lazy-initialization.md
packages/eslint-plugin-react-hooks/src/rules/prefer-use-state-lazy-initialization.spec.ts
packages/eslint-plugin-react-hooks/src/rules/prefer-use-state-lazy-initialization.ts
packages/eslint-plugin/src/index.ts
website/pages/rules/_meta.json
website/pages/rules/overview.md

feat: add rule `react-hooks/prefer-use-state-lazy-initialization`, closes #214

---

CHANGELOG.md
packages/eslint-plugin-naming-convention/src/rules/filename-extension.md
packages/eslint-plugin-naming-convention/src/rules/filename-extension.spec.ts
packages/eslint-plugin-naming-convention/src/rules/filename-extension.ts

refactor: `named-convention/filename-extension` options format, closes #217

---

packages/core/docs/README.md
packages/core/src/hook/is.ts
packages/plugins/eslint-plugin-naming-convention/src/rules/use-state.spec.ts
packages/plugins/eslint-plugin-naming-convention/src/rules/use-state.ts
packages/plugins/eslint-plugin-react-hooks/src/rules/ensure-use-callback-has-non-empty-deps.spec.ts
packages/plugins/eslint-plugin-react-hooks/src/rules/ensure-use-callback-has-non-empty-deps.ts
packages/plugins/eslint-plugin-react-hooks/src/rules/ensure-use-memo-has-non-empty-deps.spec.ts
packages/plugins/eslint-plugin-react-hooks/src/rules/ensure-use-memo-has-non-empty-deps.ts
packages/plugins/eslint-plugin-react-hooks/src/rules/prefer-use-state-lazy-initialization.spec.ts
packages/plugins/eslint-plugin-react-hooks/src/rules/prefer-use-state-lazy-initialization.ts

feat: add react hooks alias

---

CHANGELOG.md
packages/core/docs/README.md
packages/core/src/component/component-collector.ts
packages/core/src/component/component-identifier.ts
packages/core/src/component/component-name.ts
packages/plugins/eslint-plugin-debug/src/rules/function-component.spec.ts
packages/plugins/eslint-plugin-react/src/rules/no-unstable-nested-components.ts

refactor: improve function component detection

---

cspell.json
examples/vite-react-dom-ts-flat/eslint.config.js
examples/vite-react-dom-ts-flat/package.json
pnpm-lock.yaml
website/pages/docs/installation.mdx

docs: update setup for eslint flat config, closes #367

---

packages/plugins/eslint-plugin-react-core/package.json
packages/plugins/eslint-plugin-react-debug/package.json
packages/plugins/eslint-plugin-react-dom/package.json
packages/plugins/eslint-plugin-react-hooks-extra/package.json
packages/plugins/eslint-plugin-react-naming-convention/package.json
packages/plugins/eslint-plugin/package.json

feat: widen peer dependency range to support typescript-eslint v8 (fixes #554)

---

CHANGELOG.md
packages/core/docs/functions/useComponentCollector.md
packages/core/src/component/component-collector.ts
packages/plugins/eslint-plugin-react-debug/src/rules/function-component.spec.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-create-ref.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-unstable-context-value.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-unstable-default-props.ts
packages/plugins/eslint-plugin-react-x/src/rules/prefer-destructuring-assignment.spec.ts

refactor: improve 'core/component-collector'

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
dprint.json

chore: format YAML with dprint

---

packages/plugins/eslint-plugin-react-dom/src/rules/no-children-in-void-dom-elements.spec.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-children-in-void-dom-elements.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-dangerously-set-innerhtml-with-children.spec.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-dangerously-set-innerhtml-with-children.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-dangerously-set-innerhtml.spec.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-dangerously-set-innerhtml.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-missing-button-type.spec.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-missing-button-type.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-missing-iframe-sandbox.spec.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-missing-iframe-sandbox.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-namespace.spec.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-namespace.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-unsafe-iframe-sandbox.spec.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-unsafe-iframe-sandbox.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-unsafe-target-blank.spec.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-unsafe-target-blank.ts
packages/shared/docs/interfaces/ESLintReactSettings.md
packages/shared/docs/interfaces/ESLintSettings.md
packages/shared/src/schemas.ts
packages/utilities/jsx/src/get-element-name.ts
packages/utilities/jsx/src/get-element-type.ts
packages/utilities/jsx/src/index.ts
website/pages/docs/configuration.mdx

- **Removed the current incomplete lint support for `React.createElement` to improve performance and subsequent code maintainability**.

feat: add 'polymorphicPropName' support, closes #669

---

README.md

Add eslint-config-upleveled to "Who is using?" in readme

---

packages/plugins/eslint-plugin-react-hooks-extra/README.md
packages/plugins/eslint-plugin-react-naming-convention/README.md

The plugin name and the rules name do not match. This PR fixes the issue.

docs: fix rules name

---

website/pages/docs/installation.mdx

docs: fix minor errors in README.md

---

README.md

docs: update 'Who is using?' in README.md

---

CHANGELOG.md
packages/plugins/eslint-plugin-react-dom/README.md
packages/plugins/eslint-plugin-react-dom/src/index.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-unknown-property.spec.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-unknown-property.ts
packages/plugins/eslint-plugin/src/index.ts
website/pages/docs/rules/_meta.ts
website/pages/docs/rules/dom-no-unknown-property.mdx
website/pages/docs/rules/overview.md

feat(plugins/react-dom): add `no-unknown-property`, closes #846

---

README.md
packages/plugins/eslint-plugin/README.md
packages/plugins/eslint-plugin/src/index.ts
website/pages/docs/presets.mdx

feat: add recommended-typescript preset

---

website/pages/docs/rules/overview.md

docs: use correct link for `prefer-react-namespace-import` in rule list

---

packages/plugins/eslint-plugin-react-x/README.md
packages/plugins/eslint-plugin-react-x/src/index.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-forward-ref.spec.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-forward-ref.ts
packages/plugins/eslint-plugin/src/configs/all.ts
packages/plugins/eslint-plugin/src/configs/core.ts
website/pages/docs/rules/_meta.ts
website/pages/docs/rules/no-forward-ref.mdx
website/pages/docs/rules/overview.md
website/pages/roadmap.md

feat(plugins/x): add 'no-forward-ref'

---

packages/plugins/eslint-plugin-react-x/README.md
packages/plugins/eslint-plugin-react-x/src/index.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-context-provider.spec.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-context-provider.ts
packages/plugins/eslint-plugin/src/configs/all.ts
packages/plugins/eslint-plugin/src/configs/core.ts
website/pages/docs/rules/_meta.ts
website/pages/docs/rules/no-context-provider.mdx
website/pages/docs/rules/overview.md

feat(plugins/x): add 'no-context-provider'

---

packages/plugins/eslint-plugin-react-x/src/rules/no-forward-ref.spec.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-forward-ref.ts
website/pages/docs/rules/no-forward-ref.mdx

feat(plugins/x): add autofix to 'no-forward-ref', closes #871

---

packages/plugins/eslint-plugin-react-x/src/rules/no-forward-ref.spec.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-forward-ref.ts

feat(plugins/x): add destructuring props support to 'no-forward-ref'

---

packages/plugins/eslint-plugin-react-x/src/rules/no-component-will-mount.spec.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-component-will-mount.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-component-will-receive-props.spec.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-component-will-receive-props.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-component-will-update.spec.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-component-will-update.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-context-provider.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-forward-ref.ts
website/pages/docs/rules/no-component-will-mount.mdx
website/pages/docs/rules/no-component-will-receive-props.mdx
website/pages/docs/rules/no-component-will-update.mdx
website/pages/docs/rules/no-context-provider.mdx
website/pages/docs/rules/no-forward-ref.mdx
website/pages/docs/rules/overview.md

feat(plugins/x): add codemod-autofix to 'no-component-will-*'

---

website/pages/docs/rules/overview.md

docs: add 'Min. React' column to rules overview page

---

packages/plugins/eslint-plugin/README.md
packages/shared/docs/README.md
packages/shared/docs/functions/getReactVersion.md
packages/shared/package.json
packages/shared/src/get-react-version.ts
packages/shared/src/index.ts
packages/shared/src/settings.ts
pnpm-lock.yaml

refactor(shared): replace 'local-pkg' package with node built-in api

---

packages/core/docs/functions/isCallFromReact.md
packages/core/docs/functions/isCallFromReactMember.md
packages/core/docs/functions/isChildrenCountCall.md
packages/core/docs/functions/isChildrenForEachCall.md
packages/core/docs/functions/isChildrenMapCall.md
packages/core/docs/functions/isChildrenOfCreateElement.md
packages/core/docs/functions/isChildrenOnlyCall.md
packages/core/docs/functions/isChildrenToArrayCall.md
packages/core/docs/functions/isCloneElementCall.md
packages/core/docs/functions/isCreateContextCall.md
packages/core/docs/functions/isCreateElementCall.md
packages/core/docs/functions/isCreateRefCall.md
packages/core/docs/functions/isForwardRefCall.md
packages/core/docs/functions/isInsideCreateElementProps.md
packages/core/docs/functions/isMemoCall.md
packages/core/src/element/hierarchy.ts
packages/core/src/utils/is-from-react.ts
packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-unnecessary-use-callback.ts
packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-unnecessary-use-memo.ts
packages/plugins/eslint-plugin-react-naming-convention/src/rules/use-state.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-array-index-key.ts

refactor: 'is-from-react' to use dual api

---

website/pages/docs/rules/debug-is-from-react.md

docs: fix links in debug-is-from-react.md

---

website/pages/docs/rules/dom-no-dangerously-set-innerhtml.md
website/pages/docs/rules/dom-no-missing-button-type.md
website/pages/docs/rules/dom-no-missing-iframe-sandbox.md
website/pages/docs/rules/dom-no-namespace.md
website/pages/docs/rules/dom-no-render-return-value.md
website/pages/docs/rules/dom-no-script-url.md
website/pages/docs/rules/dom-no-unknown-property.md
website/pages/docs/rules/dom-no-unsafe-iframe-sandbox.md
website/pages/docs/rules/dom-no-unsafe-target-blank.md
website/pages/docs/rules/dom-no-void-elements-with-children.md

docs: fix links in rules docs

---

packages/plugins/eslint-plugin-react-x/src/rules/no-array-index-key.ts

pref: improve 'no-array-index-key'

---

apps/website/content/docs/advanced-configuration.mdx
apps/website/content/docs/configurations.mdx
packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-direct-set-state-in-use-layout-effect.spec.ts
packages/shared/src/schemas.ts

refactor: add `useEffect` to `additionalHooks`

---

packages/plugins/eslint-plugin-react-x/README.md
packages/plugins/eslint-plugin/src/configs/all.ts
packages/plugins/eslint-plugin/src/configs/core.ts

refactor: change severity of 'no-duplicate-key' rule from error to warn

---

packages/plugins/eslint-plugin-react-naming-convention/package.json
packages/plugins/eslint-plugin-react-naming-convention/src/rules/use-state.spec.ts
packages/plugins/eslint-plugin-react-naming-convention/src/rules/use-state.ts
pnpm-lock.yaml

fix: reimplement 'naming-convention/use-state', closes #953

---

packages/plugins/eslint-plugin-react-x/package.json
packages/plugins/eslint-plugin-react-x/src/rules/prefer-read-only-props.spec.ts
packages/plugins/eslint-plugin-react-x/src/rules/prefer-read-only-props.ts
pnpm-lock.yaml

fix: correct readonly checks and test cases

---

packages/plugins/eslint-plugin-react-naming-convention/src/rules/component-name.spec.ts
packages/plugins/eslint-plugin-react-naming-convention/src/rules/component-name.ts
packages/plugins/eslint-plugin-react-naming-convention/src/rules/context-name.ts

fix: improve normalization and validation in component and context name rules

---

packages/plugins/eslint-plugin-react-naming-convention/src/rules/use-state.spec.ts
packages/plugins/eslint-plugin-react-naming-convention/src/rules/use-state.ts

fix: `naming-convention/use-state` fails with multiple words, closes #960

---

apps/website/content/docs/deprecated.md
apps/website/content/docs/presets.mdx
apps/website/content/docs/rules/overview.md

docs: add deprecated rules and presets reference documentation

---

apps/website/package.json
examples/vite-react-dom-js-with-babel-eslint-parser-app/package.json
packages/plugins/eslint-plugin-react-naming-convention/src/configs/recommended.ts
packages/plugins/eslint-plugin/src/configs/recommended.ts
pnpm-lock.yaml

feat: revert 'feat: add naming-convention/use-state and naming-convention/context-name to recommended presets by @Rel1cx in #956'

---

apps/website/content/docs/rules/overview.md
packages/plugins/eslint-plugin-react-dom/src/configs/recommended.ts
packages/plugins/eslint-plugin-react-dom/src/rules/no-flush-sync.md
packages/plugins/eslint-plugin/src/configs/dom.ts

fix: update rule severity for 'no-flush-sync' and 'no-void-elements-with-children'

---

apps/website/content/docs/rules/overview.mdx
packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-unnecessary-use-prefix.ts

refactor: improve rule description and error message

---

packages/plugins/eslint-plugin-react-x/src/configs/recommended-typescript.ts
packages/plugins/eslint-plugin-react-x/src/configs/recommended.ts
packages/plugins/eslint-plugin/src/configs/core.ts

fix: recommended presets missing the 'no-useless-fragment' rule

---

packages/plugins/eslint-plugin-react-x/package.json
packages/plugins/eslint-plugin-react-x/src/rules/prefer-read-only-props.spec.ts
packages/plugins/eslint-plugin-react-x/src/rules/prefer-read-only-props.ts
pnpm-lock.yaml

fix: `prefer-read-only-props` false positive using React types, closes #962

---

.pkgs/configs/eslint.js
.pkgs/configs/eslint.ts
packages/core/src/component/component-collector.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-nested-component-definitions.spec.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-nested-component-definitions.ts

refactor(plugins/x): enhance `no-nested-component-definitions` error messages

---

apps/website/content/docs/configurations.mdx
packages/shared/src/settings.ts

chore: update default React version to 19.1.0 in documentation and settings

---

packages/plugins/eslint-plugin-react-x/src/rules/jsx-uses-react.ts

fix(react-x): fixed `jsx-uses-react` rule for `preserve` mode

---

LICENSE
package.json
packages/core/package.json
packages/plugins/eslint-plugin-react-debug/package.json
packages/plugins/eslint-plugin-react-dom/package.json
packages/plugins/eslint-plugin-react-hooks-extra/package.json
packages/plugins/eslint-plugin-react-naming-convention/package.json
packages/plugins/eslint-plugin-react-web-api/package.json
packages/plugins/eslint-plugin-react-x/package.json
packages/plugins/eslint-plugin/package.json
packages/shared/package.json
packages/utilities/ast/package.json
packages/utilities/eff/package.json
packages/utilities/jsx/package.json
packages/utilities/kit/package.json
packages/utilities/var/package.json

fix: use initial release year and consistent username in LICENSE

---

packages/utilities/ast/src/get-nested-return-statements.ts
packages/utilities/kit/docs/@eslint-react/namespaces/LanguagePreference/variables/DEFAULT_LANGUAGE_PREFERENCE.md
packages/utilities/kit/src/LanguagePreference/LanguagePreference.ts
packages/utilities/kit/src/LanguagePreference/LanguagePreferenceSchema.ts

refactor(kit): simplify `LanguagePreferenceSchema`

---

packages/shared/docs/interfaces/CustomComponentNormalized.md
packages/shared/package.json
packages/shared/src/settings.ts
pnpm-lock.yaml

pref: replace `picomatch.makeRe` with `RE.toRegExp` for pattern matching

---

packages/plugins/eslint-plugin-react-hooks-extra/src/hooks/use-no-direct-set-state-in-use-effect.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-duplicate-key.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-unstable-context-value.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-unstable-default-props.ts
packages/utilities/eff/docs/functions/getOrUpdate.md
packages/utilities/eff/src/index.ts
packages/utilities/kit/src/JsxConfig/JsxConfig.ts

perf: replace `Map` with `WeakMap` for better memory management

---

examples/vite-react-dom-app/eslint.config.js
packages/plugins/eslint-plugin-react-debug/src/rules/class-component.spec.ts
packages/plugins/eslint-plugin-react-debug/src/rules/class-component.ts
packages/plugins/eslint-plugin-react-debug/src/rules/function-component.spec.ts
packages/plugins/eslint-plugin-react-debug/src/rules/function-component.ts
packages/plugins/eslint-plugin-react-debug/src/rules/hook.spec.ts
packages/plugins/eslint-plugin-react-debug/src/rules/hook.ts
packages/plugins/eslint-plugin-react-debug/src/rules/is-from-react.spec.ts
packages/plugins/eslint-plugin-react-debug/src/rules/is-from-react.ts
packages/plugins/eslint-plugin-react-debug/src/rules/jsx.spec.ts
packages/plugins/eslint-plugin-react-debug/src/rules/jsx.ts
packages/plugins/eslint-plugin-react-debug/src/utils/index.ts
packages/plugins/eslint-plugin-react-debug/src/utils/stringify.ts

fix: better debug rules message formatting

---

.vscode/settings.json
examples/next-app/.vscode/settings.json
examples/vite-react-dom-app/.vscode/settings.json
examples/vite-react-dom-app/eslint.config.js
examples/vite-react-dom-js-app/.vscode/settings.json
examples/vite-react-dom-js-with-babel-eslint-parser-app/.vscode/settings.json
examples/vite-react-dom-with-ts-blank-eslint-parser-app/.vscode/settings.json
packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-unnecessary-use-prefix.ts

fix: use smaller error marker range in `hooks-extra/no-unnecessary-use-prefix` to reduce visual noise

---

.vscode/settings.json
apps/website/package.json
examples/next-app/.vscode/settings.json
examples/vite-react-dom-app/.vscode/settings.json
examples/vite-react-dom-app/package.json
examples/vite-react-dom-js-app/.vscode/settings.json
examples/vite-react-dom-js-app/package.json
examples/vite-react-dom-js-with-babel-eslint-parser-app/.vscode/settings.json
examples/vite-react-dom-js-with-babel-eslint-parser-app/package.json
examples/vite-react-dom-with-ts-blank-eslint-parser-app/.vscode/settings.json
examples/vite-react-dom-with-ts-blank-eslint-parser-app/package.json
package.json
packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-unnecessary-use-prefix.ts
packages/shared/package.json
packages/utilities/kit/package.json
pnpm-lock.yaml

fix: use preferred loc in error maker

---

apps/website/content/docs/configuration/configure-language-config.mdx
apps/website/content/docs/faq.mdx
apps/website/content/docs/rules/overview.mdx

docs: improve jsx-related docs

---

apps/website/content/docs/glossary.mdx
apps/website/content/docs/meta.json

docs: add glossary page

---

packages/plugins/eslint-plugin-react-x/src/rules/no-useless-fragment.ts

feat: deprecate 'no-useless-fragment' rule

---

apps/website/app/(home)/page.tsx
apps/website/app/layout.config.tsx
apps/website/app/layout.tsx
apps/website/components/ESLintReact.tsx
apps/website/components/EffectLayer.tsx

feat(website): add back light mode

---

packages/plugins/eslint-plugin-react-x/src/rules/jsx-no-iife.ts
packages/plugins/eslint-plugin-react-x/src/rules/jsx-uses-vars.ts

fix: update messages for 'react-x/jsx-no-iife' and 'react-x/jsx-uses-vars' rules

---

packages/plugins/eslint-plugin-react-x/src/rules/no-missing-context-display-name.spec.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-missing-context-display-name.ts
packages/utilities/kit/src/LanguagePreference/LanguagePreference.ts

fix: 'no-missing-context-display-name' correctly handles semicolons in autofix

---

packages/plugins/eslint-plugin-react-dom/src/rules/no-missing-button-type.ts

fix: update suggestion for 'no-missing-button-type' rule to use dynamic prop name

---

.pkgs/configs/eslint.js
.pkgs/configs/eslint.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-misused-capture-owner-stack.ts

chore: minor cleanups

---

apps/website/content/docs/community.tsx

chore: add 'clientIO/joint' project to community adoption list

---

eslint.config.ts
packages/plugins/eslint-plugin-react-hooks-extra/src/rules/no-direct-set-state-in-use-effect.md

docs: disable 'markdown/no-html' rule and add React data fetching tip

---

.pkgs/configs/package.json
.pkgs/eslint-plugin-local/package.json
apps/website/package.json
examples/next-app/package.json
examples/vite-react-dom-app/package.json
examples/vite-react-dom-js-app/package.json
examples/vite-react-dom-js-with-babel-eslint-parser-app/package.json
examples/vite-react-dom-with-ts-blank-eslint-parser-app/package.json
package.json
packages/core/src/utils/index.ts
packages/core/src/utils/is-from-react.ts
packages/plugins/eslint-plugin-react-debug/src/rules/is-from-react.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-forward-ref.spec.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-forward-ref.ts
pnpm-lock.yaml

fix: refactor is-from-react utility and improve no-forward-ref rule autofix handling, closes #1172

---

eslint.config.ts
packages/core/src/env/env-vitest.ts
packages/core/src/env/index.ts
packages/core/src/index.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-unnecessary-use-prefix.spec.ts
packages/plugins/eslint-plugin-react-x/src/rules/no-unnecessary-use-prefix.ts

feat: add vitest mock env detection, closes #1181

---

packages/core/src/hook/hook-hierarchy.ts
packages/plugins/eslint-plugin-react-web-api/src/rules/no-leaked-event-listener.spec.ts

fix: fix useEffect setup function check in `web-api/no-leaked-event-listener`, closes #1228

---

apps/website/content/docs/migration.mdx

Fix quotes consistency in migration guide
--

fix: make quotes consistent

---

.pkgs/configs/package.json
.pkgs/eslint-plugin-local/package.json
packages/plugins/eslint-plugin/package.json
pnpm-lock.yaml

fix: add `ts-api-utils` to unified plugin deps, closes #1239

---

apps/website/content/docs/configuration/configure-analyzer.mdx
apps/website/content/docs/configuration/configure-analyzer.tsx
packages/shared/src/settings.ts

Bump React version from 19.1.0 to 19.2.0
